name: Build, Push and Deploy LibreTranslate

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Variables
        id: get-variables
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "GH_USERNAME_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.GH_USERNAME_LOWER }}/libretranslate:latest

  deploy:
    name: Deploy to AWS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into AWS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "🧹 Limpando recursos antigos do Docker..."
            docker system prune -af

            echo "🔄 Pulling imagem mais recente..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/libretranslate:latest

            echo "🛑 Parando e removendo container antigo..."
            docker stop libretranslate || true
            docker rm libretranslate || true

            echo "🚀 Subindo novo container na porta 5000..."
            docker run -d \
              -p 5000:5000 \
              --name libretranslate \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/libretranslate:latest
